
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujprcyzemscysqidgvqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqcHJjeXplbXNjeXNxaWRndnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTg4NzUsImV4cCI6MjA2NDc5NDg3NX0.BqvOJPcc8OOUjrqq0VDTK-amrcbfte1MI53wnVRP7xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
